[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
    [".oh-my-zsh".clone]
        args = ["--depth", "1"]
[".zsh-custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
    [".zsh-custom/plugins/zsh-syntax-highlighting".clone]
        args = ["--depth", "1"]
[".zsh-custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
    [".zsh-custom/plugins/zsh-autosuggestions".clone]
        args = ["--depth", "1"]
[".zsh-custom/plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"
    [".zsh-custom/plugins/zsh-completions".clone]
        args = ["--depth", "1"]
