["ukill"]
    type = "git-repo"
    url = "https://gitee.com/sunn4mirror/ukill.git"
    ["ukill".clone]
        args = ["--depth", "1"]
["browser-bookmarks"]
    type = "git-repo"
    url = "https://gitee.com/sunn4open/browser-bookmarks.git"
    ["browser-bookmarks".clone]
        args = ["--depth", "1"]

