#! /bin/sh

function autostart() {
	if command -v "$1" >/dev/null 2>&1; then
		"$@" &
	else
		notify-send "$1 not found"
	fi
}
autostart sxhkd
autostart ${HOME}/.fehbg
autostart picom --experimental-backends
autostart polybar -r
autostart fcitx5
autostart xflux -l 35.5 -g 112.8
autostart nm-applet
autostart clipit
autostart ulauncher --no-window
autostart xautolock -time 10 -locker "betterlockscreen -l dim"
if [ -f "${HOME}/mainkey.txt" ] && [ -f "${HOME}/keepass.kdbx" ]; then
	cat "${HOME}/mainkey.txt" | autostart keepassxc --pw-stdin "${HOME}/keepass.kdbx"
fi

bspc monitor -d 0 1 2 3 4 5 6 7 8 9
bspc desktop 0 -l monocle
bspc desktop 9 -l monocle
bspc desktop -f 1

bspc config border_width 4
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color   "#403E41"
bspc config focused_border_color  "#78DCE8"
bspc config urgent_border_color   "#403E41"
bspc config presel_border_color   "#403E41"

bspc config external_rules_command "${HOME}/.config/bspwm/rules.sh"

bspc subscribe node_focus | while read -r line; do
	id=$(echo "$line" | awk '{print $4}')
	if bspc query -N -n $id.\!floating.window; then
		for hid in `bspc query -N -n .local.window.floating.\!hidden`; do
			bspc node $hid --flag hidden=on
		done
	fi
done &

