#! /bin/sh

xsetroot -cursor_name left_ptr

bspc monitor -d 0 1 2 3 4 5 6 7 8 9
bspc desktop 0 -l monocle
bspc desktop 3 -l monocle
bspc desktop 9 -l monocle
bspc desktop -f 1

bspc config border_width 4
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color   "#403E41"
bspc config focused_border_color  "#78DCE8"
bspc config urgent_border_color   "#403E41"
bspc config presel_border_color   "#403E41"

bspc rule -a 'Alacritty:dropdown' state=floating sticky=on locked=on
bspc rule -a 'Ulauncher' state=floating sticky=on border=off
bspc rule -a 'KeePassXC' state=floating sticky=on
bspc rule -a 'feh' state=floating sticky=on
bspc rule -a 'Thunar' state=floating sticky=on
bspc rule -a 'Lxappearance' state=floating sticky=on
bspc rule -a 'qt5ct' state=floating sticky=on
bspc rule -a 'VirtualBox Manager' desktop=9 follow=on
bspc rule -a 'VirtualBox Machine' desktop=9 follow=on
bspc rule -a 'Vivaldi-stable' desktop=2 follow=on
bspc rule -a 'Code' desktop=3 follow=on
bspc rule -a 'Zathura' state=tiled desktop=4 follow=on
bspc rule -a 'mpv' desktop=5 follow=on
bspc rule -a '*:*:Task Manager - Vivaldi' state=floating sticky=on
bspc rule -a '*:*:Picture in picture' state=floating sticky=on private=on
bspc rule -a 'Zeal' state=floating sticky=on

bspc subscribe node_focus | while read -r line; do
	if bspc query -N -n .focused.window.\!floating; then
		for id in `bspc query -N -n .window.floating.\!hidden.\!private`; do
			bspc node $id --flag hidden=on
		done
	fi
done &

function autostart() {
	if command -v "$1" >/dev/null 2>&1; then
		"$@" &
	else
		notify-send "$1 not found"
	fi
}
autostart sxhkd
autostart ${HOME}/.fehbg
autostart picom --experimental-backends
autostart polybar -r
autostart fcitx5
autostart xflux -l 35.5 -g 112.8
autostart nm-applet
autostart blueman-applet
autostart clipit
autostart ulauncher --no-window
autostart xautolock -time 10 -locker "betterlockscreen -l dim"
autostart zeal
cat ~/keepass.key | autostart keepassxc --pw-stdin ~/keepass.kdbx

